
---

```yaml
name: CI LunaGames

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore

    - name: Rodar testes
      run: dotnet test --no-restore --verbosity normal

    - name: Build da imagem Docker
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG }} .

    - name: Login no ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push da imagem Docker para o ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG }}