CREATE TABLE USERGAME (
    Id SERIAL PRIMARY KEY,
    GameId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    CONSTRAINT fk_game FOREIGN KEY (GameId) REFERENCES GAME(Id),
    CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES USERS(Id)
);