CREATE TABLE USERS (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR (20) NOT NULL
);