# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia csproj e restaura dependências
COPY *.sln .
COPY LunaGames/*.csproj ./LunaGames/
RUN dotnet restore

# Copia tudo e compila
COPY LunaGames/. ./LunaGames/
WORKDIR /app/LunaGames
RUN dotnet publish -c Release -o out

# Imagem final
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/LunaGames/out .
ENTRYPOINT ["dotnet", "LunaGames.dll"]
